version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    container_name: warehouse-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/mywarehouse"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    container_name: warehouse-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
